"use client";
import { useState } from "react";
import { ArticleOutlined, CheckCircleRounded, CloudUploadOutlined, LocationOnOutlined, MapOutlined, PersonOutlineRounded, WorkOutlineRounded } from "@mui/icons-material";

const defaults={profession:"",category:"",experience:"",district:"",skills:[],education:"",languages:[],desiredRoles:[],salaryMin:"",salaryMax:"",schedule:"full_time",workMode:"office",radiusKm:3,notifications:{site:true,push:true,email:true},cvName:""};
const radii=[1,3,5,10,25];
const array=(value)=>Array.isArray(value)?value:[];
function Field({label,children}){return <label className="profile-design-field"><span>{label}</span>{children}</label>}
function Choice({label,value,onChange,options}){return <fieldset className="profile-choice"><legend>{label}</legend>{options.map(([key,text])=><label key={key}><input type="radio" checked={value===key} onChange={()=>onChange(key)}/>{text}</label>)}</fieldset>}

export default function SeekerProfilePanel({ctx}){
 const {user,editingName,setEditingName,editingPhone,setEditingPhone,locationText,setLocationText,lat,setLat,lng,setLng,loading,handleProfileSave,handleLocationActivation,locationLoading,categories=[]}=ctx;
 const saved=user?.seekerProfile||user?.seeker_profile||{};
 const [profile,setProfile]=useState({...defaults,...saved,skills:array(saved.skills),languages:array(saved.languages),desiredRoles:array(saved.desiredRoles),notifications:{...defaults.notifications,...(saved.notifications||{})}});
 const [open,setOpen]=useState("career");
 const set=(key,value)=>setProfile(current=>({...current,[key]:value}));
 const setList=(key,value)=>set(key,value.split(",").map(item=>item.trim()).filter(Boolean));
 const checks=[profile.profession,profile.category,profile.experience,profile.cvName,profile.skills.length,profile.education,profile.desiredRoles.length,profile.salaryMin,locationText,Object.values(profile.notifications).some(Boolean)];
 const percent=Math.round(checks.filter(Boolean).length/checks.length*100);
 const notify=(key)=>setProfile(current=>({...current,notifications:{...current.notifications,[key]:!current.notifications[key]}}));
 const sections=[
  ["career","Peşə məlumatları",PersonOutlineRounded,<div className="profile-design-grid profile-design-three" key="career"><Field label="Ad, soyad"><input value={editingName} onChange={e=>setEditingName(e.target.value)} required/></Field><Field label="Peşə / vəzifə"><input value={profile.profession} onChange={e=>set("profession",e.target.value)} placeholder="Məsələn: Marketinq mütəxəssisi"/></Field><Field label="Kateqoriya"><select value={profile.category} onChange={e=>set("category",e.target.value)}><option value="">Kateqoriya seçin</option>{categories.map(item=><option key={String(item)}>{String(item)}</option>)}</select></Field><Field label="Telefon"><input value={editingPhone} onChange={e=>setEditingPhone(e.target.value)}/></Field><Field label="Təcrübə səviyyəsi"><select value={profile.experience} onChange={e=>set("experience",e.target.value)}><option value="">Seçin</option><option>Başlanğıc (0–2 il)</option><option>Orta (2–5 il)</option><option>Təcrübəli (5+ il)</option></select></Field><Field label="Rayon"><input value={profile.district} onChange={e=>set("district",e.target.value)}/></Field></div>],
  ["cv","CV və bacarıqlar",ArticleOutlined,<div key="cv"><label className="profile-upload"><CloudUploadOutlined/><strong>{profile.cvName||"CV faylınızı buraya sürükləyin və ya seçin"}</strong><small>PDF, DOCX. Maks. 10 MB</small><input type="file" accept=".pdf,.doc,.docx" onChange={e=>set("cvName",e.target.files?.[0]?.name||"")}/></label><div className="profile-design-grid profile-design-three"><Field label="Bacarıqlar"><input value={profile.skills.join(", ")} onChange={e=>setList("skills",e.target.value)} placeholder="SMM, Google Analytics, Meta Ads"/></Field><Field label="Təhsil"><select value={profile.education} onChange={e=>set("education",e.target.value)}><option value="">Seçin</option><option>Orta təhsil</option><option>Ali təhsil</option><option>Magistr</option></select></Field><Field label="Dillər"><input value={profile.languages.join(", ")} onChange={e=>setList("languages",e.target.value)}/></Field></div></div>],
  ["preferences","İş üstünlükləri",WorkOutlineRounded,<div className="profile-design-grid" key="pref"><Field label="Arzu etdiyiniz vəzifələr"><input value={profile.desiredRoles.join(", ")} onChange={e=>setList("desiredRoles",e.target.value)}/></Field><Field label="Minimum əmək haqqı (AZN)"><input inputMode="numeric" value={profile.salaryMin} onChange={e=>set("salaryMin",e.target.value.replace(/\D/g,""))}/></Field><Field label="Maksimum əmək haqqı (AZN)"><input inputMode="numeric" value={profile.salaryMax} onChange={e=>set("salaryMax",e.target.value.replace(/\D/g,""))}/></Field><Choice label="İş rejimi" value={profile.schedule} onChange={value=>set("schedule",value)} options={[["full_time","Tam ştat"],["part_time","Yarım ştat"],["shift","Növbəli"]]}/><Choice label="İş forması" value={profile.workMode} onChange={value=>set("workMode",value)} options={[["office","Ofisdə"],["hybrid","Hibrid"],["remote","Uzaqdan"]]}/></div>],
  ["location","Lokasiya və bildirişlər",LocationOnOutlined,<div key="location"><div className="profile-location-box"><div><strong>Yaxın işləri göstər</strong><div className="profile-location-actions"><button type="button" onClick={handleLocationActivation} disabled={locationLoading}><LocationOnOutlined/>{locationLoading?"Müəyyən edilir...":"Cari lokasiyamı istifadə et"}</button><button type="button"><MapOutlined/>Xəritədən seç</button></div></div><div><strong>Saxlanılan lokasiya</strong><input value={locationText} onChange={e=>setLocationText(e.target.value)} placeholder="Ev ünvanı"/></div><div><strong>Radius</strong><div className="profile-radius">{radii.map(item=><button type="button" key={item} className={Number(profile.radiusKm)===item?"active":""} onClick={()=>set("radiusKm",item)}>{item} km</button>)}</div></div></div><div className="profile-notifications"><div><strong>Yaxınlıqda yeni iş çıxanda xəbər ver</strong><small>Uyğun vakansiyalar haqqında bildiriş alın.</small></div>{[["site","Sayt bildirişləri"],["push","Push bildirişləri"],["email","E-poçt"]].map(([key,label])=><label key={key}><input type="checkbox" checked={!!profile.notifications[key]} onChange={()=>notify(key)}/>{label}</label>)}</div></div>]
 ];
 return <main className="profile-design-page"><div className="profile-design-top"><strong>Asimos</strong><div className="profile-steps"><span className="done"><CheckCircleRounded/>1 Hesab</span><span className="active"><b>2</b> Profil</span><span><b>3</b> Təsdiqləmə</span></div></div><form onSubmit={event=>handleProfileSave(event,profile)}><header className="profile-design-heading"><h1>Profilinizi tamamlayın</h1><p>Bu məlumatlar sizə uyğun vakansiyaları göstərməyə kömək edəcək.</p></header><div className="profile-design-layout"><div className="profile-design-main">{sections.map(([id,label,Icon,content])=><section className={`profile-design-section ${open===id?"open":""}`} key={id}><button type="button" className="profile-mobile-toggle" onClick={()=>setOpen(open===id?"":id)}><Icon/>{label}<span>⌄</span></button><div className="profile-section-content"><h2>{label}</h2>{content}</div></section>)}</div><aside className="profile-design-aside"><section><h3>Profil tamamlanma faizi</h3><strong className="profile-percent">{percent}%</strong><div className="profile-progress"><span style={{width:`${percent}%`}}/></div><p>{percent<100?"Əla! Bir az da məlumat əlavə edin.":"Profiliniz tam hazırdır."}</p></section><section><h3>Tövsiyə olunanlar</h3>{["Profil şəklinizi əlavə edin","Peşə və kateqoriya seçin","CV əlavə edin","Bacarıqlarınızı qeyd edin","İş üstünlüklərinizi müəyyən edin","Lokasiyanı tamamlayın"].map((item,index)=><span className={index<Math.ceil(percent/17)?"done":""} key={item}><CheckCircleRounded/>{item}</span>)}</section><section className="profile-match"><h3>Sizə uyğun nəticə</h3><strong>{profile.district||"Bakı"}da {profile.radiusKm} km radius</strong><b>{12+profile.skills.length*5+profile.desiredRoles.length*8}</b><small>uyğun vakansiya</small></section></aside></div><input className="seeker-hidden-location" value={lat} onChange={e=>setLat(e.target.value)} aria-label="Lat"/><input className="seeker-hidden-location" value={lng} onChange={e=>setLng(e.target.value)} aria-label="Lng"/><footer className="profile-design-footer"><button type="button" onClick={()=>setOpen("career")}>Geri</button><button type="submit" disabled={loading}>{loading?"Yadda saxlanılır...":"Davam et"}</button></footer></form></main>;
}
